#!/bin/sh

unamestr=$(uname)
if [ "$unamestr" = 'Linux' ]
then
    CC=gcc
    CXX=g++
    PLATFORM=linux
    LINUXFLAG=-ldl
else
    CC=cc
    CXX=c++
    PLATFORM=bsd
fi

# current directory
ROOT=$PWD

# your install directory
INSTALL_DIR=${ROOT}/build_$CC/luadch

# open ssl header files
OPENSSL_HEADER_DIR=/usr/include/openssl

# open ssl libraries
OPENSSL_LIB_DIR=/usr/lib

# hopefully nothing to edit below

echo Copy core...
mkdir -p ${INSTALL_DIR}/log
mkdir -p ${INSTALL_DIR}/lib/adclib
mkdir -p ${INSTALL_DIR}/lib/unicode
mkdir -p ${INSTALL_DIR}/lib/luasocket/socket
mkdir -p ${INSTALL_DIR}/lib/luasocket/mime
mkdir -p ${INSTALL_DIR}/lib/luasocket/lua
mkdir -p ${INSTALL_DIR}/lib/luasec/ssl
mkdir -p ${INSTALL_DIR}/lib/luasec/lua
mkdir -p ${INSTALL_DIR}/lib/basexx
rsync -a ${ROOT}/core ${INSTALL_DIR}/
rsync -a ${ROOT}/scripts ${INSTALL_DIR}/
rsync -a ${ROOT}/examples/cfg ${INSTALL_DIR}/
rsync -a ${ROOT}/examples/certs ${INSTALL_DIR}/
rsync -a ${ROOT}/examples/lang ${INSTALL_DIR}/
rsync -a ${ROOT}/docs ${INSTALL_DIR}/

LUA_DIR=${ROOT}/lua/src

echo Building lua...
cd ${ROOT}/lua/src
make CC=$CC INSTALL_DIR=$INSTALL_DIR

clean() {
    if [ "$1" = "clean" ]
    then
        make clean
    fi
}

echo Building adclib...
cd ${ROOT}/adclib
make CXX=$CXX LUAINCLUDE_DIR=$LUA_DIR LUALIB_DIR=$INSTALL_DIR INSTALL_DIR=$INSTALL_DIR/lib/adclib/adclib.so
clean $1

echo Building slnunicode...
cd ${ROOT}/slnunicode
make CC=$CC LUAINCLUDE_DIR=$LUA_DIR LUALIB_DIR=$INSTALL_DIR INSTALL_DIR=$INSTALL_DIR/lib/unicode/unicode.so
clean $1

echo Building luasocket...
cd ${ROOT}/luasocket/
make PLAT=$PLATFORM LUAINC_linux=$LUA_DIR LUAINC_bsd=$LUA_DIR
cp ./src/socket*.so $INSTALL_DIR/lib/luasocket/socket/socket.so
cp ./src/mime*.so $INSTALL_DIR/lib/luasocket/mime/mime.so
cp ./src/*.lua $INSTALL_DIR/lib/luasocket/lua/

echo Building luasec...
cd ${ROOT}/luasec
make $PLATFORM INC_PATH=-I$LUA_DIR LIB_PATH=-L$INSTALL_DIR
cp ./src/ssl.so $INSTALL_DIR/lib/luasec/ssl/ssl.so
cp ./src/*.lua $INSTALL_DIR/lib/luasec/lua/
clean $1

echo Building basexx...
cd ${ROOT}/basexx
make CC=$CC LUAINCLUDE_DIR=$LUA_DIR LUALIB_DIR=$INSTALL_DIR INSTALL_DIR=$INSTALL_DIR/lib/basexx/
clean $1

if [ "$1" = "jit" ]
then
    echo Building luajit...
    cd ${ROOT}/luajit
    if [ $PLATFORM = "linux" ]
    then
        make
    else
        gmake
    fi
    LUAFLAG=-lluajit
    cp ./src/libluajit.so $INSTALL_DIR/libluajit.so
    ln $INSTALL_DIR/libluajit.so $INSTALL_DIR/libluajit-5.1.so.2
else
    LUAFLAG=-llua
fi

echo Building hub...
cd ${ROOT}/hub
make CC=$CC LUAFLAG=$LUAFLAG LINUXFLAG=$LINUXFLAG LUAINCLUDE_DIR=$LUA_DIR LUALIB_DIR=$INSTALL_DIR INSTALL_DIR=$INSTALL_DIR
clean $1

