#!/bin/sh

# current directory
ROOT=$PWD

# your install directory
INSTALL_DIR=${ROOT}/build_gcc/luadch

# open ssl header files
OPENSSL_HEADER_DIR=/usr/include/openssl

# open ssl libraries
OPENSSL_LIB_DIR=/usr/lib

# hopefully nothing to edit below

unamestr=$(uname)
if [ "$unamestr" = 'Linux' ]
then
    CC=gcc
    CXX=g++
    PLATFORM=linux
    LINUXFLAG=-ldl
else
    CC=cc
    CXX=c++
    PLATFORM=bsd
fi

echo Copy core...
mkdir -p ${INSTALL_DIR}/log
mkdir -p ${INSTALL_DIR}/lib/adclib
mkdir -p ${INSTALL_DIR}/lib/unicode
mkdir -p ${INSTALL_DIR}/lib/luasocket/socket
mkdir -p ${INSTALL_DIR}/lib/luasocket/mime
mkdir -p ${INSTALL_DIR}/lib/luasocket/lua
mkdir -p ${INSTALL_DIR}/lib/luasec/ssl
mkdir -p ${INSTALL_DIR}/lib/luasec/lua
mkdir -p ${INSTALL_DIR}/lib/basexx
rsync -a ${ROOT}/core ${INSTALL_DIR}/
rsync -a ${ROOT}/scripts ${INSTALL_DIR}/
rsync -a ${ROOT}/examples/cfg ${INSTALL_DIR}/
rsync -a ${ROOT}/examples/certs ${INSTALL_DIR}/
rsync -a ${ROOT}/examples/lang ${INSTALL_DIR}/
rsync -a ${ROOT}/docs ${INSTALL_DIR}/

if [ "$1" = "jit" ]
then
    LUA_DIR=${ROOT}/luajit
    echo Building luajit...
    cd ${ROOT}/luajit
    make
    cp ./src/libluajit.so $INSTALL_DIR/liblua.so
    make clean
else
    LUA_DIR=${ROOT}/lua/src
    echo Building lua...
    cd ${ROOT}/lua/src
    make CC=$CC INSTALL_DIR=$INSTALL_DIR
    make clean
fi

echo Building adclib...
cd ${ROOT}/adclib
make CXX=$CXX LUAINCLUDE_DIR=$LUA_DIR LUALIB_DIR=$INSTALL_DIR INSTALL_DIR=$INSTALL_DIR/lib/adclib/adclib.so
make clean

echo Building slnunicode-1.1a...
cd ${ROOT}/slnunicode-1.1a
make CC=$CC LUAINCLUDE_DIR=$LUA_DIR LUALIB_DIR=$INSTALL_DIR INSTALL_DIR=$INSTALL_DIR/lib/unicode/unicode.so
make clean

echo Building luasocket-3.0...
cd ${ROOT}/luasocket-3.0/
make PLAT=$PLATFORM LUAINC_linux=$LUA_DIR LUAINC_bsd=$LUA_DIR
cp ./src/socket*.so $INSTALL_DIR/lib/luasocket/socket/socket.so
cp ./src/mime*.so $INSTALL_DIR/lib/luasocket/mime/mime.so
cp ./src/*.lua $INSTALL_DIR/lib/luasocket/lua/

echo Building luasec-6.1...
cd ${ROOT}/luasec-6.1
make $PLATFORM INC_PATH=-I$LUA_DIR LIB_PATH=-L$INSTALL_DIR
cp ./src/ssl.so $INSTALL_DIR/lib/luasec/ssl/ssl.so
cp ./src/*.lua $INSTALL_DIR/lib/luasec/lua/
make clean

echo Building basexx...
cd ${ROOT}/basexx
make CC=$CC LUAINCLUDE_DIR=$LUA_DIR LUALIB_DIR=$INSTALL_DIR INSTALL_DIR=$INSTALL_DIR/lib/basexx/
make clean

echo Building hub...
cd ${ROOT}/hub
make CC=$CC LINUXFLAG=$LINUXFLAG LUAINCLUDE_DIR=$LUA_DIR LUALIB_DIR=$INSTALL_DIR INSTALL_DIR=$INSTALL_DIR
make clean

